Algoritmo "olamundo"
// Disciplina: Introdução a Lógica de Programação
// Professor: Wesley Oliveira
// Descrição: Algoritmo que fará o nosso primeiro "Olá Mundo"
// Autor(a): Leonardo Luciano de Souza 
// Data atual: 14/09/2024

// Seção de Declarações das variáveis 
var nome: caractere
    idade: inteiro

inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Olá Mundo! Meu nome é: ")
nome <- "Wesley"
escreval(nome)
idade <- 24
escreva("Tenho")
escreva(idade)
escreva(" anos")

Fimalgoritmo