Algoritmo "olamundo"
// Disciplina   : curso de programação web
// Professor   : Wesley Oliveira
// Descrição   :   fazer uma ola mundo
// Autor(a)    : Leonardo Souza
// Data atual  : 11/08/2022

// Seção de Declarações das variáveis
Var nome:caractere
idade: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval("olá mundo ")
 nome <- "léo"
 idade<-13
 escreva("meu nome é ")
escreval (nome)
escreva ("minha idade é")
escreva(idade)
Fimalgoritmo