Algoritmo "trocadevalores"

Var  numero1, numero2, numero3: inteiro

Inicio
escreva("digite um numero: ")
 leia(numero1)
 escreva("digite outro numero:")
 leia(numero2)
 
 
 escreval(numero1)
 escreval(numero2)
 
   //escreval(numero2)
    //escreval(numero1)
    
               numero3 <- numero1
    
               numero1 <- numero2
               numero2 <- numero3

                escreval(numero1)
                escreval(numero2)
Fimalgoritmo